# Generated by Django 3.2.15 on 2022-08-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20220823_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название месторождения')),
                ('uid', models.CharField(max_length=150, verbose_name='Уникальный месторождения')),
                ('description', models.TextField(blank=True, verbose_name='Описание месторождения')),
                ('geo', models.CharField(max_length=500, verbose_name='Координаты расположения')),
            ],
        ),
        migrations.CreateModel(
            name='PurposeWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название назначения')),
                ('description', models.TextField(blank=True, verbose_name='Описание назначения')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StatusWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название статуса')),
                ('description', models.TextField(blank=True, verbose_name='Описание статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название скважины')),
                ('uid', models.CharField(max_length=150, verbose_name='Уникальный идентификатор')),
                ('nameLegal', models.CharField(max_length=150, verbose_name='Юридическое название скважины')),
                ('numLicense', models.CharField(max_length=150, verbose_name='Лицензионный номер скважины')),
                ('dTimLicense', models.DateField(verbose_name='Дата и время выдачи лицензии')),
                ('country', models.CharField(max_length=150, verbose_name='Страна, в которой находится скважина')),
                ('state', models.CharField(max_length=150, verbose_name='Штат или провинция, в которой находится скважина')),
                ('county', models.CharField(max_length=150, verbose_name='Район, в котором находится скважина')),
                ('region', models.CharField(max_length=150, verbose_name='Геополитический регион')),
                ('district', models.CharField(max_length=150, verbose_name='Название геополитического района')),
                ('block', models.CharField(max_length=150, verbose_name='Имя блока, в котором находится скважина')),
                ('timeZone', models.CharField(help_text='Это отклонение в часах и минутах от UTC. Это должен быть обычный часовой пояс на скважине, а не значение с учетом сезонных колебаний, такое как летнее время', max_length=150, verbose_name='Часовой пояс, в котором находится скважина')),
                ('operatorDiv', models.CharField(max_length=150, verbose_name='Подразделение операторской компании')),
                ('dTimSpud', models.DateField(verbose_name='Дата и время забуривания скважины')),
                ('dTimPa', models.DateField(verbose_name='Дата и время закрытия скважины')),
                ('wellheadElevation', models.CharField(max_length=150, verbose_name='Высота устья скважины относительно исходной точки')),
                ('groundElevation', models.CharField(help_text='Наземные буровые установки', max_length=150, verbose_name='Высота над уровнем земли')),
                ('waterDepth', models.CharField(help_text='Не наземные буровые установки', max_length=150, verbose_name='Глубина воды')),
                ('dTimCreation', models.DateField(auto_now_add=True, verbose_name='Дата и время забуривания скважины')),
                ('dTimLastChange', models.DateField(auto_now=True, verbose_name='Последнее изменение любого элемента данных')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии и замечания')),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='well.field', verbose_name='Название месторождения, в котором находится скважина')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Название компании-оператора')),
                ('purposeWell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='well.purposewell', verbose_name='POSC назначение скважины')),
                ('statusWell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='well.statuswell', verbose_name='POSC Состояние скважины')),
            ],
            options={
                'verbose_name': 'Скважину',
                'verbose_name_plural': 'Скважины',
                'ordering': ('name',),
            },
        ),
    ]
