# Generated by Django 3.2.15 on 2022-08-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('short_name',), 'verbose_name': 'Компанию', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('reliable', 'Надежый'), ('indefined', 'Статус неопределен'), ('unreliable', 'Ненадежный')], default='indefined', max_length=10, verbose_name='Статус'),
        ),
    ]
