# Generated by Django 3.2.15 on 2022-08-31 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название оборудования')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный идентификатор')),
                ('banner', models.ImageField(blank=True, upload_to='equipment_banners/', verbose_name='Изображение оборудования')),
                ('description', models.TextField(blank=True, verbose_name='Описание оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ('name',),
            },
        ),
    ]
