# Generated by Django 3.2.15 on 2022-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('name',), 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='banner',
            field=models.ImageField(blank=True, upload_to='equipment_banners/', verbose_name='Изображение оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='uid',
            field=models.CharField(max_length=150, verbose_name='Уникальный идентификатор'),
        ),
    ]
