# Generated by Django 3.2.15 on 2022-08-31 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название буровой установки')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный идентификатор')),
                ('banner', models.ImageField(blank=True, upload_to='rig_banners/', verbose_name='Изображение буровой установки')),
                ('description', models.TextField(blank=True, verbose_name='Описание буровой установки')),
                ('status', models.CharField(choices=[('working', 'Работает'), ('not_working', 'Не работает'), ('scheduled_maintenance', 'На плановом ремонте'), ('unknown', 'Статус неизвестен')], default='not_working', max_length=30, verbose_name='Состояние буровой установки')),
                ('equipments', models.ManyToManyField(blank=True, to='equipment.Equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Буровую установку',
                'verbose_name_plural': 'Буровые установки',
                'ordering': ('name',),
            },
        ),
    ]
