# Generated by Django 3.2.15 on 2022-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_auto_20220824_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название оборудования')),
                ('uid', models.CharField(max_length=150, verbose_name='Уникальный идентификатор')),
                ('banner', models.ImageField(blank=True, upload_to='rig_banners/', verbose_name='Изображение буровой установки')),
                ('status', models.CharField(choices=[('working', 'Черновик'), ('not_working', 'Не работает'), ('scheduled_maintenance', 'На плановом ремонте')], default='not_working', max_length=30, verbose_name='Состояние буровой установки')),
                ('equipments', models.ManyToManyField(blank=True, to='equipment.Equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Буровую установку',
                'verbose_name_plural': 'Буровые установки',
                'ordering': ('name',),
            },
        ),
    ]
