# Generated by Django 3.2.15 on 2022-08-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rig', '0002_rig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='status',
            field=models.CharField(choices=[('working', 'Работает'), ('not_working', 'Не работает'), ('scheduled_maintenance', 'На плановом ремонте'), ('unknown', 'Статус неизвестен')], default='not_working', max_length=30, verbose_name='Состояние буровой установки'),
        ),
    ]
